### ISSUE TITLE
Could not be served

### ISSUE THREAD

**Issue by MoroccanGeek** [crisbeto/angular-svg-round-progressbar#213]
After installing it, I tried to serve my app but it gives me this : 

`Compiling angular-svg-round-progressbar : module as esm5
Warning: Invalid constructor parameter decorator in D:/Hence Projects/Twitter-Harvester/node_modules/angular-svg-round-progressbar/fesm2015/angular-svg-round-progressbar.js:
 () => [
    { type: undefined, decorators: [{ type: Optional }, { type: Inject, args: [DOCUMENT,] }] }
]
Error: Error on worker #1: Error: getInternalNameOfClass() called on a non-ES5 class: expected RoundProgressService to have an inner class declaration
    at Esm5ReflectionHost.getInternalNameOfClass`

**Comment by BenRacicot** [comment]
I can confirm this warning which breaks compilation on Angular ^9 setups.

```
Warning: Invalid constructor parameter decorator in /Users/z277888/dev/ng-ice/node_modules/angular-svg-round-progressbar/fesm2015/angular-svg-round-progressbar.js:
 () => [
    { type: undefined, decorators: [{ type: Optional }, { type: Inject, args: [DOCUMENT,] }] }
]
Error: Error on worker #5: Error: getInternalNameOfClass() called on a non-ES5 class: expected RoundProgressService to have an inner class declaration
```

**Comment by nijeshw** [comment]
```[ng] ✘ [ERROR] No matching export in "node_modules/@angular/core/fesm2022/core.mjs" for import "DOCUMENT"
[ng]     node_modules/angular-svg-round-progressbar/fesm2022/angular-svg-round-progressbar.mjs:2:9:
[ng]       2 │ import { DOCUMENT, Injectable, Optional, Inject, InjectionToken, Ev...
[ng]         ╵          ~~~~~~~~
[ng] /Users/nijeshw/DriverUp/transport-tech-app/node_modules/esbuild/lib/main.js:1463
[ng]   let error = new Error(text);
[ng]               ^
[ng] Error: Build failed with 1 error:
[ng] node_modules/angular-svg-round-progressbar/fesm2022/angular-svg-round-progressbar.mjs:2:9: ERROR: No matching export in "node_modules/@angular/core/fesm2022/core.mjs" for import "DOCUMENT"
[ng]     at failureErrorWithLog (/Users/nijeshw/DriverUp/transport-tech-app/node_modules/esbuild/lib/main.js:1463:15)
[ng]     at /Users/nijeshw/DriverUp/transport-tech-app/node_modules/esbuild/lib/main.js:924:25
[ng]     at /Users/nijeshw/DriverUp/transport-tech-app/node_modules/esbuild/lib/main.js:1341:9
[ng]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[ng]   errors: [Getter/Setter],
[ng]   warnings: [Getter/Setter]
[ng] }
[ng] Node.js v22.3.0

[ERROR] ng has unexpectedly closed (exit code 1).
```

After installing getting error.

**Comment by AAlghareeb-WSS** [comment]
I got the same error after upgrading angular to 19
